[package]
name = "spotick"
version = "0.1.0"
edition = "2021"
authors = ["Dominik Strutz"]
description = "Simple and lightweight Windows widget for Spotify"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.99"
slint = { version = "1.12.1", features = ["renderer-winit-skia"] }

[build-dependencies]
slint-build = "1.12.1"
