import { Button } from "button.slint";
export component OptionsButton inherits Button {
    width: 20px;
    height: 20px;
    border-radius: 20px;

    callback on-close();
    callback on-options();
    in property <string> more-vert: "M480-160q-33 0-56.5-23.5T400-240q0-33 23.5-56.5T480-320q33 0 56.5 23.5T560-240q0 33-23.5 56.5T480-160Zm0-240q-33 0-56.5-23.5T400-480q0-33 23.5-56.5T480-560q33 0 56.5 23.5T560-480q0 33-23.5 56.5T480-400Zm0-240q-33 0-56.5-23.5T400-720q0-33 23.5-56.5T480-800q33 0 56.5 23.5T560-720q0 33-23.5 56.5T480-640Z";

    clicked => {
        options.show();
    }

    Path {
        stroke: #d4d4d4;
        fill: #d4d4d4;
        commands: more-vert;
        transform-scale: 0.6;
    }

    options := PopupWindow {
        width: 70px;
        height: 80px;
        close-policy: PopupClosePolicy.close-on-click-outside;
        x: parent.width - options.width;

        Rectangle {
            border-radius: 12px;
            background: #383838;

            VerticalLayout {
                padding: 7px;
                Button {
                    hover-background-color: #0b4cbc;
                    border-radius: 5px;
                    clicked => {
                        options.close();
                        on-options();
                    }
                    Text {
                        text: "Options";
                    }
                }

                Button {
                    hover-background-color: #d35454;
                    border-radius: 5px;
                    clicked => {
                        on-close()
                    }
                    Text {
                        text: "Close";
                    }
                }
            }
        }
    }
}
