import { Button } from "Button.slint";
export component OptionsButton inherits Button {
    width: 20px;
    height: 20px;
    border-radius: 20px;

    callback on-close();
    callback on-options();

    clicked => {
        options.show();
    }

    Text {
        text: "⁝";
        font-size: 16px;
    }

    options := PopupWindow {
        width: 70px;
        height: 80px;
        close-policy: PopupClosePolicy.close-on-click-outside;
        x: parent.width - options.width;

        Rectangle {
            border-radius: 12px;
            background: #383838;

            VerticalLayout {
                padding: 7px;
                Button {
                    hover-background-color: #20772f;
                    border-radius: 5px;
                    clicked => {
                        options.close();
                        on-options();
                    }
                    Text {
                        text: "Options";
                    }
                }
                Button {
                    hover-background-color: #d35454;
                    border-radius: 5px;
                    clicked => {on-close()}
                    Text {
                        text: "Close";
                    }
                }
            }
        }
    }
}
