import { OptionsButton } from "widgets/OptionsButton.slint";
import { MediaButton, MediaButtonType } from "widgets/MediaButton.slint";

export component AppWindow inherits Window {
    height: 200px;
    width: 440px;
    no-frame: true;
    title: "Spotick";
    background: rgba(0,0,0,0);

    in-out property <length> window-x;
    in-out property <length> window-y;
    out property <length> thumbnail-border-radius: 8px;
    out property <image> thumbnail-placeholder: @image-url("assets/thumbnail-placeholder.png");
    in property <image> thumbnail-img: thumbnail-placeholder;
    in property <string> track-title: "No Track";
    in property <string> track-subtitle: "...";
    in property <bool> playing: false;

    function move-window() {
        window-x += (ta.current-position.x - ta.pressed-position.x);
        window-y += (ta.current-position.y - ta.pressed-position.y);
        position-window(window-x, window-y);
    }

    callback close();
    callback position-window(x: length, y: length);
    callback togglePlay();
    callback nextTrack();
    callback previousTrack();

    ta := SwipeGestureHandler {
        moved => {move-window()}
        Rectangle {
            background: @linear-gradient(130deg, #0a3018 0%, #0c612d 100%);
            border-radius: 16px;

            VerticalLayout {
                HorizontalLayout {
                    padding: 10px;
                    padding-bottom: 0;
                    alignment: LayoutAlignment.end;
                    OptionsButton {
                        on-close => {close()}
                    }
                }
                HorizontalLayout {
                    padding-left: 25px;
                    padding-right: 10px;
                    padding-top: 10px;
                    spacing: 30px;
                    Image {
                        width: 128px;
                        height: 128px;
                        image-fit: ImageFit.fill;
                        source: thumbnail-img;
                    }
                    VerticalLayout {
                        alignment: LayoutAlignment.start;
                        spacing: 5px;
                        Text {
                            text: track-title;
                            font-size: 30px;
                        }
                        Text {
                            text: track-subtitle;
                        }
                        Rectangle {
                            height: 20px;
                            
                        }
                        HorizontalLayout {
                            spacing: 25px;
                            VerticalLayout {
                                alignment: LayoutAlignment.center;
                                MediaButton {
                                    btn-type: MediaButtonType.Previous;
                                    size: 30px;
                                    clicked => {previousTrack()}
                                }
                            }
                            MediaButton {
                                clicked => {togglePlay();}
                                btn-type: playing ? MediaButtonType.Pause : MediaButtonType.Play;
                            }
                            VerticalLayout {
                                alignment: LayoutAlignment.center;
                                MediaButton {
                                    btn-type: MediaButtonType.Next;
                                    size: 30px;
                                    clicked => {nextTrack()}
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
