import { Button } from "widgets/button.slint";
import { LineEdit, Switch, Slider } from "std-widgets.slint";
import { AnnotatedSlider } from "widgets/step-slider.slint";

component SettingsText inherits Text {
    font-size: 1.2rem;
    vertical-alignment: TextVerticalAlignment.center;
    horizontal-alignment: TextHorizontalAlignment.left;
}

export enum MsgType {
    Success,
    Error,
    Info
}

export component SlintSettingsWindow inherits Window {
    title: "Spotick Settings";
    width: 400px;
    height: 300px;
    background: #1c1c1c;

    in-out property <bool> auto-start <=> auto-start-switch.checked;
    in-out property <bool> always-top <=> on-top-switch.checked;
    in-out property <string> media-application-id: "";
    in-out property <float> window-scale: 1;

    callback settings-changed();
    callback scale-changed();

    public function show-msg(msg: string, type: MsgType) {
        msg-text-timer.running = false;
        msg-text.text = msg;
        if type == MsgType.Success {
            msg-text.color = Colors.green;
        } else if type == MsgType.Error {
            msg-text.color = Colors.red;
        } else {
            msg-text.color = Colors.aliceblue.darker(0.25);
        }
        msg-text.visible = true;
        msg-text-timer.running = true;
    }

    VerticalLayout {
        padding: 15px;
        alignment: LayoutAlignment.start;
        spacing: 10px;
        GridLayout {
            spacing: 10px;
            spacing-vertical: 15px;
            Row {
                SettingsText {text: "Autostart";}
                auto-start-switch := Switch {
                    toggled => {settings-changed()}
                }
            }
            Row {
                SettingsText {text: "Always on top";}
                on-top-switch := Switch {
                    toggled => {settings-changed()}
                }
            }
            Row {
                SettingsText {text: "Media application";}
                LineEdit {
                    text <=> media-application-id;
                }
                Button {
                    background-color: gray.darker(0.7);
                    hover-background-color: gray.darker(0.9);
                    width: 80px;
                    height: 30px;
                    border-radius: 4px;
                    clicked => {
                        if !media-application-id.is-empty {
                            settings-changed();
                        }
                    }
                    Text {
                        text: "Confirm";
                        font-size: 1.5rem;
                    }
                }
            }
            Row {
                SettingsText {text: "UI Scale";}
                AnnotatedSlider {
                    colspan: 2;
                    steps: [0.5, 1, 1.5, 2];
                    value <=> window-scale;
                    changed(value) => {
                        scale-changed();
                    }
                }
            }
        }
        msg-text := Text {
            visible: false;
            font-size: 20px;
        }
    }
    
    msg-text-timer := Timer {
        interval: 3000ms;
        running: false;
        triggered => {
            msg-text-timer.running = false;
            msg-text.visible = false;
        }
    }
}
