import { Button } from "widgets/Button.slint";
import { Switch } from "widgets/Switch.slint";

component SettingsText inherits Text {
    font-size: 1.2rem;
    vertical-alignment: TextVerticalAlignment.center;
    horizontal-alignment: TextHorizontalAlignment.left;
}

component SettingsRow inherits Rectangle {
    in property <string> name;
    HorizontalLayout {
        alignment: LayoutAlignment.space-between;
        SettingsText {text: name;}
        @children
    }
}

export component SlintSettingsWindow inherits Window {
    title: "Spotick Settings";
    width: 400px;
    height: 300px;
    background: #1c1c1c;

    HorizontalLayout {
        alignment: LayoutAlignment.start;
        padding: 10px;
        VerticalLayout {
            width: 50%;
            spacing: 15px;
            alignment: LayoutAlignment.start;
            SettingsRow {
                name: "Spotify";
                Button {
                    background-color: gray.darker(0.7);
                    hover-background-color: gray.darker(0.9);
                    width: 80px;
                    height: 30px;
                    border-radius: 4px;
                    Text {
                        text: "Connect";
                        font-size: 1.5rem;
                    }
                }
            }
            SettingsRow {
                name: "Autostart";
                Switch {}
            }
        }
    }
}
